<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from de.systopia.remoteevent/xml/schema/CRM/Remoteevent/ParticipantSession.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:cdf7660b6dafd42d179840488a21a024)
 */

/**
 * Database access object for the ParticipantSession entity.
 */
class CRM_Remoteevent_DAO_ParticipantSession extends CRM_Core_DAO {

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_participant_session';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique Session Participant ID
   *
   * @var int
   */
  public $id;

  /**
   * FK to Session
   *
   * @var int
   */
  public $session_id;

  /**
   * FK to Participant ID
   *
   * @var int
   */
  public $participant_id;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_participant_session';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   */
  public static function getEntityTitle() {
    return ts('Participant Sessions');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'session_id', 'civicrm_session', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'participant_id', 'civicrm_participant', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Remoteevent_ExtensionUtil::ts('Unique Session Participant ID'),
          'required' => TRUE,
          'where' => 'civicrm_participant_session.id',
          'table_name' => 'civicrm_participant_session',
          'entity' => 'ParticipantSession',
          'bao' => 'CRM_Remoteevent_DAO_ParticipantSession',
          'localizable' => 0,
          'add' => NULL,
        ],
        'session_id' => [
          'name' => 'session_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Remoteevent_ExtensionUtil::ts('FK to Session'),
          'where' => 'civicrm_participant_session.session_id',
          'table_name' => 'civicrm_participant_session',
          'entity' => 'ParticipantSession',
          'bao' => 'CRM_Remoteevent_DAO_ParticipantSession',
          'localizable' => 0,
          'FKClassName' => 'CRM_Remoteevent_DAO_Session',
          'add' => NULL,
        ],
        'session_participant_id' => [
          'name' => 'participant_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => CRM_Remoteevent_ExtensionUtil::ts('Session Participant'),
          'description' => CRM_Remoteevent_ExtensionUtil::ts('FK to Participant ID'),
          'required' => TRUE,
          'import' => TRUE,
          'where' => 'civicrm_participant_session.participant_id',
          'export' => TRUE,
          'table_name' => 'civicrm_participant_session',
          'entity' => 'ParticipantSession',
          'bao' => 'CRM_Remoteevent_DAO_ParticipantSession',
          'localizable' => 0,
          'FKClassName' => 'CRM_Event_DAO_Participant',
          'add' => '1.7',
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'participant_session', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'participant_session', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
