<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from de.systopia.remoteevent/xml/schema/CRM/Remoteevent/Session.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:0f720e3ec3d0710e38886449b46ee10f)
 */
use CRM_Remoteevent_ExtensionUtil as E;

/**
 * Database access object for the Session entity.
 */
class CRM_Remoteevent_DAO_Session extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_session';

  /**
   * Field to show when displaying a record.
   *
   * @var string
   */
  public static $_labelField = 'title';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique Session ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * FK to Event
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $event_id;

  /**
   * Session Title
   *
   * @var string|null
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $title;

  /**
   * Is this Session enabled or disabled/cancelled?
   *
   * @var bool|string|null
   *   (SQL type: tinyint)
   *   Note that values will be retrieved from the database as a string.
   */
  public $is_active;

  /**
   * Date and time that sessions starts.
   *
   * @var string|null
   *   (SQL type: datetime)
   *   Note that values will be retrieved from the database as a string.
   */
  public $start_date;

  /**
   * Date and time that session ends. May be NULL if no defined end date/time
   *
   * @var string|null
   *   (SQL type: datetime)
   *   Note that values will be retrieved from the database as a string.
   */
  public $end_date;

  /**
   * All sessions _can_ be assigned to slots. A participant can only register for one session per slot
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $slot_id;

  /**
   * Session category
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $category_id;

  /**
   * Session type
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $type_id;

  /**
   * Full description of the session. Text and html allowed. Displayed on built-in Event Information screens.
   *
   * @var string|null
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $description;

  /**
   * Maximum number of registered participants to allow.
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $max_participants;

  /**
   * Location information for this session
   *
   * @var string|null
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $location;

  /**
   * FK to Contact ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $presenter_id;

  /**
   * Presenter Title
   *
   * @var string|null
   *   (SQL type: varchar(127))
   *   Note that values will be retrieved from the database as a string.
   */
  public $presenter_title;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_session';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Sessions') : E::ts('Session');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'event_id', 'civicrm_event', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'presenter_id', 'civicrm_contact', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique Session ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_session.id',
          'table_name' => 'civicrm_session',
          'entity' => 'Session',
          'bao' => 'CRM_Remoteevent_DAO_Session',
          'localizable' => 0,
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'event_id' => [
          'name' => 'event_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Event ID'),
          'description' => E::ts('FK to Event'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_session.event_id',
          'table_name' => 'civicrm_session',
          'entity' => 'Session',
          'bao' => 'CRM_Remoteevent_DAO_Session',
          'localizable' => 0,
          'FKClassName' => 'CRM_Event_DAO_Event',
          'html' => [
            'type' => 'EntityRef',
          ],
          'pseudoconstant' => [
            'table' => 'civicrm_event',
            'keyColumn' => 'id',
            'labelColumn' => 'title',
            'prefetch' => 'false',
          ],
          'add' => NULL,
        ],
        'session_title' => [
          'name' => 'title',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Session Title'),
          'description' => E::ts('Session Title'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_session.title',
          'export' => TRUE,
          'table_name' => 'civicrm_session',
          'entity' => 'Session',
          'bao' => 'CRM_Remoteevent_DAO_Session',
          'localizable' => 1,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'is_active' => [
          'name' => 'is_active',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Is Active'),
          'description' => E::ts('Is this Session enabled or disabled/cancelled?'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_session.is_active',
          'default' => '1',
          'table_name' => 'civicrm_session',
          'entity' => 'Session',
          'bao' => 'CRM_Remoteevent_DAO_Session',
          'localizable' => 0,
          'html' => [
            'type' => 'CheckBox',
          ],
          'add' => NULL,
        ],
        'session_start_date' => [
          'name' => 'start_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => E::ts('Session Start Date'),
          'description' => E::ts('Date and time that sessions starts.'),
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_session.start_date',
          'export' => TRUE,
          'table_name' => 'civicrm_session',
          'entity' => 'Session',
          'bao' => 'CRM_Remoteevent_DAO_Session',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
            'formatType' => 'activityDateTime',
          ],
          'add' => NULL,
        ],
        'session_end_date' => [
          'name' => 'end_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => E::ts('Session End Date'),
          'description' => E::ts('Date and time that session ends. May be NULL if no defined end date/time'),
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_session.end_date',
          'headerPattern' => '/^end|(e(nd\s)?date)$/i',
          'export' => TRUE,
          'table_name' => 'civicrm_session',
          'entity' => 'Session',
          'bao' => 'CRM_Remoteevent_DAO_Session',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
            'formatType' => 'activityDateTime',
          ],
          'add' => NULL,
        ],
        'session_slot_id' => [
          'name' => 'slot_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Session Slot'),
          'description' => E::ts('All sessions _can_ be assigned to slots. A participant can only register for one session per slot'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_session.slot_id',
          'table_name' => 'civicrm_session',
          'entity' => 'Session',
          'bao' => 'CRM_Remoteevent_DAO_Session',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
          ],
          'pseudoconstant' => [
            'optionGroupName' => 'session_slot',
            'optionEditPath' => 'civicrm/admin/options/session_slot',
          ],
          'add' => NULL,
        ],
        'session_category_id' => [
          'name' => 'category_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Session Category'),
          'description' => E::ts('Session category'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_session.category_id',
          'table_name' => 'civicrm_session',
          'entity' => 'Session',
          'bao' => 'CRM_Remoteevent_DAO_Session',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
          ],
          'pseudoconstant' => [
            'optionGroupName' => 'session_category',
            'optionEditPath' => 'civicrm/admin/options/session_category',
          ],
          'add' => NULL,
        ],
        'session_type_id' => [
          'name' => 'type_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Session Type'),
          'description' => E::ts('Session type'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_session.type_id',
          'table_name' => 'civicrm_session',
          'entity' => 'Session',
          'bao' => 'CRM_Remoteevent_DAO_Session',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
          ],
          'pseudoconstant' => [
            'optionGroupName' => 'session_type',
            'optionEditPath' => 'civicrm/admin/options/session_type',
          ],
          'add' => NULL,
        ],
        'session_description' => [
          'name' => 'description',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('session Description'),
          'description' => E::ts('Full description of the session. Text and html allowed. Displayed on built-in Event Information screens.'),
          'rows' => 8,
          'cols' => 60,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_session.description',
          'table_name' => 'civicrm_session',
          'entity' => 'Session',
          'bao' => 'CRM_Remoteevent_DAO_Session',
          'localizable' => 1,
          'html' => [
            'type' => 'RichTextEditor',
          ],
          'add' => NULL,
        ],
        'max_participants' => [
          'name' => 'max_participants',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Max Participants'),
          'description' => E::ts('Maximum number of registered participants to allow.'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_session.max_participants',
          'default' => '0',
          'table_name' => 'civicrm_session',
          'entity' => 'Session',
          'bao' => 'CRM_Remoteevent_DAO_Session',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'session_location' => [
          'name' => 'location',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('session Description'),
          'description' => E::ts('Location information for this session'),
          'rows' => 8,
          'cols' => 60,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_session.location',
          'table_name' => 'civicrm_session',
          'entity' => 'Session',
          'bao' => 'CRM_Remoteevent_DAO_Session',
          'localizable' => 1,
          'html' => [
            'type' => 'RichTextEditor',
          ],
          'add' => NULL,
        ],
        'session_presenter_id' => [
          'name' => 'presenter_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Presenter (Contact)'),
          'description' => E::ts('FK to Contact ID'),
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_session.presenter_id',
          'export' => TRUE,
          'table_name' => 'civicrm_session',
          'entity' => 'Session',
          'bao' => 'CRM_Remoteevent_DAO_Session',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
          'html' => [
            'type' => 'EntityRef',
          ],
          'pseudoconstant' => [
            'table' => 'civicrm_contact',
            'keyColumn' => 'id',
            'labelColumn' => 'display_name',
            'prefetch' => 'false',
          ],
          'add' => '1.7',
        ],
        'session_presenter_title' => [
          'name' => 'presenter_title',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Presenter Title'),
          'description' => E::ts('Presenter Title'),
          'maxlength' => 127,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_session.presenter_title',
          'export' => TRUE,
          'table_name' => 'civicrm_session',
          'entity' => 'Session',
          'bao' => 'CRM_Remoteevent_DAO_Session',
          'localizable' => 1,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return CRM_Core_DAO::getLocaleTableName(self::$_tableName);
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'session', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'session', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'UI_session_is_active' => [
        'name' => 'UI_session_is_active',
        'field' => [
          0 => 'is_active',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_session::0::is_active',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
