<?php
/*-------------------------------------------------------+
| SYSTOPIA Remote Event Extension                        |
| Copyright (C) 2020 SYSTOPIA                            |
| Author: B. Endres (endres@systopia.de)                 |
+--------------------------------------------------------+
| This program is released as free software under the    |
| Affero GPL license. You can redistribute it and/or     |
| modify it under the terms of this license which you    |
| can read by viewing the included agpl.txt or online    |
| at www.gnu.org/licenses/agpl.html. Removal of this     |
| copyright header is strictly prohibited without        |
| written permission from the original author(s).        |
+--------------------------------------------------------*/

declare(strict_types = 1);

use Civi\RemoteEvent;
use Civi\RemoteParticipant\Event\UpdateEvent as UpdateEvent;
use CRM_Remoteevent_ExtensionUtil as E;

/**
 * RemoteParticipant.update specification
 * @param array $spec
 *   API specification blob
 */
function _civicrm_api3_remote_participant_update_spec(&$spec) {
  $spec['event_id']          = [
    'name'         => 'event_id',
    'api.required' => 0,
    'title'        => E::ts('Event ID'),
    'description'  => E::ts('Internal ID of the event the registration form is needed for'),
  ];
  $spec['profile']           = [
    'name'         => 'profile',
    'api.required' => 0,
    'title'        => E::ts('Profile Name'),
    'description'  => E::ts('If omitted, the default profile is used'),
  ];
  $spec['remote_contact_id'] = [
    'name'         => 'remote_contact_id',
    'api.required' => 0,
    'title'        => E::ts('Remote Contact ID'),
    'description'  => E::ts('You can submit a remote contact ID, to determine the CiviCRM contact'),
  ];
  $spec['token'] = [
    'name'         => 'token',
    'api.required' => 0,
    'title'        => E::ts('Remote Registration Token'),
    'description'  => E::ts('You can cancel with a as generated by emails'),
  ];
  $spec['locale']            = [
    'name'         => 'locale',
    'api.required' => 0,
    'title'        => E::ts('Locale'),
    'description'  => E::ts('Locale of the field labels/etc. NOT IMPLEMENTED YET'),
  ];
}

/**
 * RemoteParticipant.submit: Will validate the submission/registration data
 *   and return a list of errors for the given fields
 *
 * @param array $params
 *   API call parameters
 *
 * @return array
 *   API3 response
 *
 * @throws CRM_Core_Exception
 */
function civicrm_api3_remote_participant_update($params) {
  unset($params['check_permissions']);

  // first: validate (again)
  try {
    $params['context'] = 'update';
    $validation_result = civicrm_api3('RemoteParticipant', 'validate', $params);
    if (!empty($validation_result['values'])) {
      $errors = $validation_result['values'];
      return RemoteEvent::createStaticAPI3Error(reset($errors), ['errors' => $errors]);
    }
  }
  catch (CRM_Core_Exception $ex) {
    if (isset($ex->getErrorData()['values'])) {
      $errors = $ex->getErrorData()['values'];
    }
    else {
      $errors = [$ex->getMessage()];
    }
    return RemoteEvent::createStaticAPI3Error(reset($errors), ['errors' => $errors]);
  }

  // create a transaction
  $update_transaction = new CRM_Core_Transaction();

  // dispatch to the various handlers
  $update_event = new UpdateEvent($params);
  try {
    Civi::dispatcher()->dispatch(UpdateEvent::NAME, $update_event);
  }
  catch (Exception $ex) {
    $update_event->addError($ex->getMessage());
  }

  // evaluate the result
  if ($update_event->hasErrors()) {
    // something went wrong...
    $update_transaction->rollback();
    return $update_event->createAPI3Error();

  }
  else {
    $update_transaction->commit();
    $participant = civicrm_api3('Participant', 'getsingle', ['id' => $update_event->getParticipantID()]);
    $null = NULL;

    return $update_event->createAPI3Success('RemoteParticipant', 'update', 1, [
      'event_id' => $participant['event_id'],
      'participant_id' => $participant['id'],
      'participant_role' => $participant['participant_role'],
      'participant_status' => $participant['participant_status'],
      'participant_class' => CRM_Remoteevent_Registration::getParticipantStatusClass(
        $participant['participant_status_id']
      ),
    ]);
  }
}
