-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_participant_session`;
DROP TABLE IF EXISTS `civicrm_session`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_session
-- *
-- * Event sessions and workshops
-- *
-- *******************************************************/
CREATE TABLE `civicrm_session` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique Session ID',
  `event_id` int unsigned NOT NULL COMMENT 'FK to Event',
  `title` varchar(255) COMMENT 'Session Title',
  `is_active` tinyint DEFAULT 1 COMMENT 'Is this Session enabled or disabled/cancelled?',
  `start_date` datetime COMMENT 'Date and time that sessions starts.',
  `end_date` datetime COMMENT 'Date and time that session ends. May be NULL if no defined end date/time',
  `slot_id` int unsigned COMMENT 'All sessions _can_ be assigned to slots. A participant can only register for one session per slot',
  `category_id` int unsigned COMMENT 'Session category',
  `type_id` int unsigned COMMENT 'Session type',
  `description` text COMMENT 'Full description of the session. Text and html allowed. Displayed on built-in Event Information screens.',
  `max_participants` int unsigned DEFAULT 0 COMMENT 'Maximum number of registered participants to allow.',
  `location` text COMMENT 'Location information for this session',
  `presenter_id` int unsigned COMMENT 'FK to Contact ID',
  `presenter_title` varchar(127) COMMENT 'Presenter Title',
  PRIMARY KEY (`id`),
  INDEX `UI_session_is_active`(is_active),
  CONSTRAINT FK_civicrm_session_event_id FOREIGN KEY (`event_id`) REFERENCES `civicrm_event`(`id`) ON DELETE CASCADE,
  CONSTRAINT FK_civicrm_session_presenter_id FOREIGN KEY (`presenter_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE SET NULL
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_participant_session
-- *
-- * Participant of an event session/workshop
-- *
-- *******************************************************/
CREATE TABLE `civicrm_participant_session` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique Session Participant ID',
  `session_id` int unsigned NOT NULL COMMENT 'FK to Session',
  `participant_id` int unsigned NOT NULL COMMENT 'FK to Participant',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_participant_session_session_id FOREIGN KEY (`session_id`) REFERENCES `civicrm_session`(`id`) ON DELETE CASCADE,
  CONSTRAINT FK_civicrm_participant_session_participant_id FOREIGN KEY (`participant_id`) REFERENCES `civicrm_participant`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;
